import assert from 'node:assert/strict';
import test from 'node:test';
let policy;
try { policy = await import('../../bridge/policy.mjs'); } catch {}
const request = {version:1,userUid:'student-a',instance:'pilot',deliveryHash:'a'.repeat(64),oldWork:null,newWork:'defense-a'};
const delivery = {deliveryHash:'a'.repeat(64),instances:{pilot:{works:['defense-a','defense-b']}},questions:['course/q1','course/q2','course/q3','course/bonus'],works:[{id:'defense-a',policy:{assignment:{'student-label':'label-a'}},completion:{questionIds:['course/q1','course/q2','course/q3','course/bonus'],requiredQuestionIds:['course/q1','course/q2','course/q3'],atLeast:2,fullyCompletedScore:1}},{id:'defense-b',policy:{assignment:{'student-label':'label-b'}},completion:{questionIds:['course/q1'],requiredQuestionIds:['course/q1'],atLeast:1,fullyCompletedScore:1}}]};
test('manifest bounds request and resolves labels without accepting label IDs',()=>{assert.ok(policy); assert.equal(policy.resolveAssignment(request,delivery).newLabel,'label-a'); assert.throws(()=>policy.resolveAssignment({...request,labelId:'99'},delivery)); assert.throws(()=>policy.resolveAssignment({...request,newWork:'foreign'},delivery)); assert.throws(()=>policy.resolveAssignment({...request,deliveryHash:'b'.repeat(64)},delivery));});
test('duplicate version idempotent but stale/conflicting version rejected',()=>{assert.ok(policy); const prior={...request}; assert.equal(policy.assignmentTransition(request,prior),'duplicate'); assert.throws(()=>policy.assignmentTransition({...request,newWork:'defense-b'},prior)); assert.throws(()=>policy.assignmentTransition({...request,version:0},prior)); assert.throws(()=>policy.assignmentTransition({...request,version:2,newWork:'defense-b'},prior)); assert.equal(policy.assignmentTransition({...request,version:2,oldWork:'defense-a',newWork:'defense-b'},prior),'apply');});
test('weighted_partial_does_not_count_as_two and optional never replaces required',()=>{assert.ok(policy); const work=delivery.works[0]; const rows=[{qualifiedId:'course/q1',score:1,status:'complete'},{qualifiedId:'course/q2',score:0.99,status:'complete'},{qualifiedId:'course/q3',score:0,status:'complete'},{qualifiedId:'course/bonus',score:1,status:'complete'}]; assert.deepEqual(policy.completion(work,rows),{completedRequired:1,requiredCount:3,atLeast:2,passed:false}); assert.throws(()=>policy.completion(work,[...rows,rows[0]])); assert.throws(()=>policy.completion(work,[{qualifiedId:'other/q',score:1,status:'complete'}]));});
test('first assignment requires null old work; revocation keeps immutable identity',()=>{assert.ok(policy); assert.throws(()=>policy.assignmentTransition({...request,oldWork:'defense-a'},null)); assert.throws(()=>policy.assignmentTransition({...request,version:2,userUid:'student-b',oldWork:'defense-a'},request)); assert.equal(policy.assignmentTransition({...request,version:2,oldWork:'defense-a',newWork:null},request),'apply');});
test('canonical keys use Unicode scalar order across BMP private use and astral characters',()=>{assert.equal(typeof policy.canonicalJSONString,'function');assert.equal(policy.canonicalJSONString({'𐀀':2,'\ue000':1}),'{"":1,"𐀀":2}');assert.equal(policy.canonicalJSONString({nested:{'𐀀':2,'\ue000':1},values:[2,1]}),'{"nested":{"":1,"𐀀":2},"values":[2,1]}');});
test('ambiguous configured delivery and instance binding is rejected',()=>{assert.equal(typeof policy.validateBindings,'function');const b={courseInstanceId:'1',delivery};policy.validateBindings([b]);assert.throws(()=>policy.validateBindings([b,{...b,courseInstanceId:'2'}]));});

test('canonical numeric-looking keys remain lexical rather than JS enumeration order',()=>{assert.equal(policy.canonicalJSONString({'2':'two','10':'ten'}),'{"10":"ten","2":"two"}');});
test('gateway bridge fails closed for development runtime or missing Community identity',()=>{assert.equal(typeof policy.assertProductionRuntime,'function');policy.assertProductionRuntime('production',{devMode:false,hasShib:true});assert.throws(()=>policy.assertProductionRuntime('development',{devMode:false,hasShib:true}));assert.throws(()=>policy.assertProductionRuntime('production',{devMode:true,hasShib:true}));assert.throws(()=>policy.assertProductionRuntime('production',{devMode:false,hasShib:false}));});
